language: php
services:
  - mysql

sudo: false

cache:
  directories:
  - vendor

php:
  - 7.0
  - 7.1
before_install:
  - mysql -e 'CREATE DATABASE reddogs-oauth2-server'  
install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

branches:
  only:
    - master