language: php
services:
  - mysql

sudo: false

cache:
  directories:
  - vendor

php:
  - 7.0
  - 7.1
before_install:
  - mysql -e 'CREATE DATABASE reddogs_oauth2_server'  
install:
  - travis_retry composer install --no-interaction --prefer-source
before_script:
  - vendor/bin/reddogs-migrations migrations:migrate-all
script:
  - vendor/bin/phpunit

branches:
  only:
    - master